### ISSUE TITLE
Would this project work for me to download the videos uploaded in the last 24 hours of a specific hashtag?

### ISSUE THREAD

**Issue by Root-FTW** [TobyG74/tiktok-api-dl#10]
Would this project work for me to download the videos uploaded in the last 24 hours of a specific hashtag?

For example, could I download the videos uploaded in the last 24 hours with the hashtag #fortnite ?

Thanks

**Comment by TobyG74** [comment]
This module can't download specific videos using hashtags yet, maybe I'll try adding it in the next update
