### ISSUE TITLE
Options for TikTokStalk

### ISSUE THREAD

**Issue by TanerKp** [TobyG74/tiktok-api-dl#12]
First of all, thanks for the repo!

Can you give options for the TikTokStalk function so that you can choose how many posts you want to scrape from a user?

And is there a way to get more than 35 Posts?

**Comment by TobyG74** [comment]
Hi, Sorry for late reply.

First of all, I thank you for using this repository.

Currently Tiktok has changed its results, so it can no longer display posts for users. I will always update developments on this repository
