### ISSUE TITLE
Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by saya-yukimi** [TobyG74/tiktok-api-dl#14]
![image](https://github.com/TobyG74/tiktok-api-dl/assets/161682134/1fcd6132-6ddf-4376-833e-61859368574d)

**Comment by feelemptyhere** [comment]
yeah, v1 error

**Comment by maradona4** [comment]
same here error v1, i'm work v3

**Comment by TobyG74** [comment]
Yes, I'm looking for a solution regarding that. I'm trying several ways, please just wait until I find the newest method

**Comment by exx0dusss** [comment]
Appreciate it bro

**Comment by TobyG74** [comment]
Try the latest commit that I just updated
