### ISSUE TITLE
Right side of assignment cannot be destructured

### ISSUE THREAD

**Issue by Adedoyin-Emmanuel** [TobyG74/tiktok-api-dl#16]
I'm using TypeScript with Bun to test before implementing it in my app but I keep getting this error. I changed the file to JavaScript and it works fine. I got the response and all 

<img width="1680" alt="tiktok error" src="https://github.com/TobyG74/tiktok-api-dl/assets/88517758/4c72ff5c-0c84-44ad-b846-b92ed7472ea5">

**Comment by TobyG74** [comment]
I have fixed the problem in the latest version, please try again
