### ISSUE TITLE
Tiktok.downloader is not a function

### ISSUE THREAD

**Issue by anpinghuang** [TobyG74/tiktok-api-dl#17]
![image](https://github.com/TobyG74/tiktok-api-dl/assets/118650416/a4a369a2-cde9-46b7-be35-7fa79ab570bf)

**Comment by TobyG74** [comment]
I think there was an error compiling the typescript. Because when you try **export default** it always becomes the default object.

You can use it like this:
```js
import TikAPI from "@tobyg74/tiktok-api-dl"
const { default: Tiktok } = TikAPI
...
```

Or you can use the Tiktok object directly

```js
import { Tiktok } from "@tobyg74/tiktok-api-dl"
...
```
