### ISSUE TITLE
[ QUESTION ] How Can I get tiktok cookie

### ISSUE THREAD

**Issue by rizxyu** [TobyG74/tiktok-api-dl#18]
hellow, how can i get tiktok cookie?

**Comment by TobyG74** [comment]
You can use cookies in the form of object or string

Method 1 (String) :
Login to the [Tiktok website](https://tiktok/.com) -> Open the **Inspect Element** or you can press the shortcut **CTRL + SHIFT + I** -> Go to network -> Find the request that goes to tiktok then open the request and look for **Cookie**

![Capture](https://github.com/TobyG74/tiktok-api-dl/assets/32604979/c516e5e8-7b8f-43cb-aa2e-2bbe92944dac)

Method 2 (Object) :
You can use the chrome extension [EditThisCookies](https://chromewebstore.google.com/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg) -> Login to the [Tiktok website](https://tiktok/.com) -> Then open the **EditThisCookie** extension -> Then click **Export Cookie**

![Capture2](https://github.com/TobyG74/tiktok-api-dl/assets/32604979/fa0e4bc7-a646-4551-a974-160881a98198)

**Comment by rizxyu** [comment]
what is the name of the cookie?
