### ISSUE TITLE
Posts empty in Stalk User

### ISSUE THREAD

**Issue by arislanhaikal** [TobyG74/tiktok-api-dl#19]
I try get user profile and posts feed with Tiktok.StalkUser();

But why **posts** return empty array?

And after trying to hit or refresh several times, the **posts** data will appear.

Is there something wrong? And can you fix it?

And is it possible to add a function to get posts feed by username?

Thank you for this tool!

**Comment by TobyG74** [comment]
Use cookies to avoid empty data on posts

![Capture](https://github.com/TobyG74/tiktok-api-dl/assets/32604979/daa1923b-3b70-4286-9e15-b332800407e8)

**Comment by arislanhaikal** [comment]
Nice, work perfectly
This is my bad 😓
Thank you

**Comment by arislanhaikal** [comment]
Hi @TobyG74
Can you limit posts results?
If all posts showing, for big artists it takes a long time.

Maybe, can add params number to make dynamic post result

**Comment by TobyG74** [comment]
Update to the latest version, I've solved that problem @arislanhaikal
