### ISSUE TITLE
ERROR Request failed with status code 403

### ISSUE THREAD

**Issue by duongnv1996** [TobyG74/tiktok-api-dl#21]
Hi Team,
I got error when using this lib in Nextjs production.

Tiktok.download .... response   403 error: 
`{
  "status": "error",
  "message": "Request failed with status code 403"
}`

This error not happen in localhost. only run in server happen.
Please check and help

**Comment by TobyG74** [comment]
The "v1" API cannot be used for all regions, there are several regions that are blocked, such as the "us" region. Maybe for the next update i will add the option to use a proxy
