### ISSUE TITLE
Add TikTok "photo" to valid URL

### ISSUE THREAD

**Issue by thinkpadmaster** [TobyG74/tiktok-api-dl#23]
The Tiktok slide URL is marked as an invalid link e.g: `https://www.tiktok.com/@binance/photo/7364097008107326763`

It might be better to add the "photo" slug to the regex pattern.

**Comment by gamersindo1223** [comment]
const TiktokURLregex = /https:\/\/(?:m|www|vm|vt)?\.?tiktok\.com\/((?:.*\b(?:(?:usr|v|embed|user|video|photo)\/|\?shareId=|\&item_id=)(\d+))|\w+)/;

**Comment by TobyG74** [comment]
Please try again guys, I've updated it.
