### ISSUE TITLE
Failed to get the request form error on V3 version

### ISSUE THREAD

**Issue by KunalK25** [TobyG74/tiktok-api-dl#24]
Hello author, i was using this API this morning and it was working fine but now when i try to make an request to download music with the V3 version of the API, it gives me an error saying "failed to get the request form error" so is there any suggestions on what the problem could be? I would really appreciate if you resolve this issue, thanks.

My Code:
![tt-error](https://github.com/TobyG74/tiktok-api-dl/assets/89345486/eff6d8f6-3155-485a-b3b8-e0bf9bb9741d)

Console Error:
![image](https://github.com/TobyG74/tiktok-api-dl/assets/89345486/a4a6cb55-e8a3-40e8-be4b-f1b4b8275f19)

**Comment by RiskevO3** [comment]
The web of MusicalDown is currently offline rn, thats why the request is fail

**Comment by TobyG74** [comment]
I've updated it to the latest version. Please update to version 1.1.9

**Comment by KunalK25** [comment]
> I've updated it to the latest version. Please update to version 1.1.9

I have updated to version 1.1.9 and attempted to use the V3 version of the API and It does work sometimes, It has worked twice today for me but the same problem of { status: 'error', message: 'Failed to get the request form!' } still exists even when i am using a rotating proxy so if you could look into it a little more and try to resolve this issue. I appreciate the effort, thanks.

**Comment by TobyG74** [comment]
> > I've updated it to the latest version. Please update to version 1.1.9
> 
> I have updated to version 1.1.9 and attempted to use the V3 version of the API and It does work sometimes, It has worked twice today for me but the same problem of { status: 'error', message: 'Failed to get the request form!' } still exists even when i am using a rotating proxy so if you could look into it a little more and try to resolve this issue. I appreciate the effort, thanks.

Is the tiktok url really valid? if yes, try sending it to me, because when I tried several times it still worked, I wanted to try to see if there was a difference in response

**Comment by nyansterowo** [comment]
@TobyG74 it stopped working again, gives the same error (failed to get the request form) v1.1.9
