### ISSUE TITLE
Cannot read property 'responseUrl' of undefined 

### ISSUE THREAD

**Issue by exitdump** [TobyG74/tiktok-api-dl#9]
const getApiData = async () => {
    const url = 'https://www.tiktok.com/@babulhossain2165/video/7283850685949529345'

    TiktokDL(url)
    .then( result => {
      return result.json();
    }).then( json => console.log(json) )
    .catch( err => {
      console.log('There has been a problem with your fetch operation: ' + err.message);
      throw err;
    })

using with React Native

**Comment by TobyG74** [comment]
Try again using version 2

`TiktokDL(url, { version: "v2" })`
